# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\tka\source\repos\visu\visu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1536, 879)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.load_wfm_dataset_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_wfm_dataset_button.setMinimumSize(QtCore.QSize(250, 0))
        self.load_wfm_dataset_button.setMaximumSize(QtCore.QSize(400, 25))
        self.load_wfm_dataset_button.setObjectName("load_wfm_dataset_button")
        self.verticalLayout_2.addWidget(self.load_wfm_dataset_button)
        self.load_saved_dataset_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_saved_dataset_button.setMinimumSize(QtCore.QSize(250, 0))
        self.load_saved_dataset_button.setMaximumSize(QtCore.QSize(400, 25))
        self.load_saved_dataset_button.setObjectName("load_saved_dataset_button")
        self.verticalLayout_2.addWidget(self.load_saved_dataset_button)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.process_dc_button = QtWidgets.QPushButton(self.centralwidget)
        self.process_dc_button.setObjectName("process_dc_button")
        self.verticalLayout_2.addWidget(self.process_dc_button)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.min_dc_slider = QtWidgets.QSlider(self.centralwidget)
        self.min_dc_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_dc_slider.setObjectName("min_dc_slider")
        self.verticalLayout_2.addWidget(self.min_dc_slider)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.min_dc_label = QtWidgets.QLabel(self.centralwidget)
        self.min_dc_label.setObjectName("min_dc_label")
        self.horizontalLayout_5.addWidget(self.min_dc_label)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.max_dc_label = QtWidgets.QLabel(self.centralwidget)
        self.max_dc_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_dc_label.setObjectName("max_dc_label")
        self.horizontalLayout_5.addWidget(self.max_dc_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.max_dc_slider = QtWidgets.QSlider(self.centralwidget)
        self.max_dc_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_dc_slider.setObjectName("max_dc_slider")
        self.verticalLayout_2.addWidget(self.max_dc_slider)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.min2_dc_label = QtWidgets.QLabel(self.centralwidget)
        self.min2_dc_label.setObjectName("min2_dc_label")
        self.horizontalLayout_8.addWidget(self.min2_dc_label)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_8.addWidget(self.label_17)
        self.max2_dc_label = QtWidgets.QLabel(self.centralwidget)
        self.max2_dc_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max2_dc_label.setObjectName("max2_dc_label")
        self.horizontalLayout_8.addWidget(self.max2_dc_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.process_fft_button = QtWidgets.QPushButton(self.centralwidget)
        self.process_fft_button.setObjectName("process_fft_button")
        self.verticalLayout_2.addWidget(self.process_fft_button)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.min_fft_slider = QtWidgets.QSlider(self.centralwidget)
        self.min_fft_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_fft_slider.setObjectName("min_fft_slider")
        self.verticalLayout_2.addWidget(self.min_fft_slider)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.max_fft_slider = QtWidgets.QSlider(self.centralwidget)
        self.max_fft_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_fft_slider.setObjectName("max_fft_slider")
        self.verticalLayout_2.addWidget(self.max_fft_slider)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_9.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_9.addWidget(self.label_23)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.fft_to_velocity_button = QtWidgets.QPushButton(self.centralwidget)
        self.fft_to_velocity_button.setObjectName("fft_to_velocity_button")
        self.verticalLayout_2.addWidget(self.fft_to_velocity_button)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.spacing_text = QtWidgets.QLineEdit(self.centralwidget)
        self.spacing_text.setObjectName("spacing_text")
        self.horizontalLayout_10.addWidget(self.spacing_text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.save_all_images_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_all_images_button.setObjectName("save_all_images_button")
        self.verticalLayout_2.addWidget(self.save_all_images_button)
        self.export_dc_fft_vel_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_dc_fft_vel_button.setObjectName("export_dc_fft_vel_button")
        self.verticalLayout_2.addWidget(self.export_dc_fft_vel_button)
        self.begin_alignment_button = QtWidgets.QPushButton(self.centralwidget)
        self.begin_alignment_button.setObjectName("begin_alignment_button")
        self.verticalLayout_2.addWidget(self.begin_alignment_button)
        self.export_orientation_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_orientation_button.setObjectName("export_orientation_button")
        self.verticalLayout_2.addWidget(self.export_orientation_button)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.sample_name_text = QtWidgets.QLineEdit(self.centralwidget)
        self.sample_name_text.setObjectName("sample_name_text")
        self.verticalLayout_2.addWidget(self.sample_name_text)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.x_delta_text = QtWidgets.QLineEdit(self.centralwidget)
        self.x_delta_text.setObjectName("x_delta_text")
        self.horizontalLayout_4.addWidget(self.x_delta_text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.y_delta_text = QtWidgets.QLineEdit(self.centralwidget)
        self.y_delta_text.setObjectName("y_delta_text")
        self.horizontalLayout_3.addWidget(self.y_delta_text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_12.addWidget(self.label_26)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.scan_speed_text = QtWidgets.QLineEdit(self.centralwidget)
        self.scan_speed_text.setObjectName("scan_speed_text")
        self.horizontalLayout_12.addWidget(self.scan_speed_text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_17.addWidget(self.label_31)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.laser_frequency_text = QtWidgets.QLineEdit(self.centralwidget)
        self.laser_frequency_text.setObjectName("laser_frequency_text")
        self.horizontalLayout_17.addWidget(self.laser_frequency_text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.angle_spacing_text = QtWidgets.QLineEdit(self.centralwidget)
        self.angle_spacing_text.setObjectName("angle_spacing_text")
        self.horizontalLayout_14.addWidget(self.angle_spacing_text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scan_collection_tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_collection_tabs.sizePolicy().hasHeightForWidth())
        self.scan_collection_tabs.setSizePolicy(sizePolicy)
        self.scan_collection_tabs.setMinimumSize(QtCore.QSize(1000, 700))
        self.scan_collection_tabs.setMaximumSize(QtCore.QSize(1000, 880))
        self.scan_collection_tabs.setTabPosition(QtWidgets.QTabWidget.South)
        self.scan_collection_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.scan_collection_tabs.setTabsClosable(True)
        self.scan_collection_tabs.setObjectName("scan_collection_tabs")
        self.reference_angle_tab = QtWidgets.QWidget()
        self.reference_angle_tab.setObjectName("reference_angle_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.reference_angle_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gfx_pane_vlayout = QtWidgets.QVBoxLayout()
        self.gfx_pane_vlayout.setObjectName("gfx_pane_vlayout")
        self.verticalLayout_5.addLayout(self.gfx_pane_vlayout)
        self.scan_collection_tabs.addTab(self.reference_angle_tab, "")
        self.angle_tab_1 = QtWidgets.QWidget()
        self.angle_tab_1.setObjectName("angle_tab_1")
        self.scan_collection_tabs.addTab(self.angle_tab_1, "")
        self.verticalLayout.addWidget(self.scan_collection_tabs)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1536, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.scan_collection_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VISU | 2.1.0-alpha"))
        self.load_wfm_dataset_button.setText(_translate("MainWindow", "Load WFM Dataset"))
        self.load_saved_dataset_button.setText(_translate("MainWindow", "Load Saved Dataset"))
        self.process_dc_button.setText(_translate("MainWindow", "Process DC Values"))
        self.label_11.setText(_translate("MainWindow", "Minimum Cutoff"))
        self.min_dc_label.setText(_translate("MainWindow", "min"))
        self.label_7.setText(_translate("MainWindow", "volts"))
        self.max_dc_label.setText(_translate("MainWindow", "max"))
        self.label_12.setText(_translate("MainWindow", "Maximum Cutoff"))
        self.min2_dc_label.setText(_translate("MainWindow", "min"))
        self.label_17.setText(_translate("MainWindow", "volts"))
        self.max2_dc_label.setText(_translate("MainWindow", "max"))
        self.process_fft_button.setText(_translate("MainWindow", "Process FFT Values"))
        self.label_19.setText(_translate("MainWindow", "Minimum Cutoff"))
        self.label_8.setText(_translate("MainWindow", "min"))
        self.label_9.setText(_translate("MainWindow", "MHz"))
        self.label_10.setText(_translate("MainWindow", "max"))
        self.label_20.setText(_translate("MainWindow", "Maximum Cutoff"))
        self.label_21.setText(_translate("MainWindow", "min"))
        self.label_22.setText(_translate("MainWindow", "MHz"))
        self.label_23.setText(_translate("MainWindow", "max"))
        self.fft_to_velocity_button.setText(_translate("MainWindow", "Convert FFT to Velocity Map"))
        self.label_24.setText(_translate("MainWindow", "Spacing [micron]:"))
        self.save_all_images_button.setText(_translate("MainWindow", "Save All Images to Directory"))
        self.export_dc_fft_vel_button.setText(_translate("MainWindow", "Export DC/Vel/FFT as CSV"))
        self.begin_alignment_button.setText(_translate("MainWindow", "Begin Alignment Procedure"))
        self.export_orientation_button.setText(_translate("MainWindow", "Export Orientation as CSV"))
        self.label.setText(_translate("MainWindow", "Sample Information"))
        self.label_2.setText(_translate("MainWindow", "Sample Name"))
        self.label_4.setText(_translate("MainWindow", "x-delta [mm]:"))
        self.label_3.setText(_translate("MainWindow", "y-delta [mm]:"))
        self.label_26.setText(_translate("MainWindow", "scan speed [mm/s]:"))
        self.label_31.setText(_translate("MainWindow", "laser frequency [kHz]:"))
        self.label_28.setText(_translate("MainWindow", "angle spacing [deg]:"))
        self.scan_collection_tabs.setTabText(self.scan_collection_tabs.indexOf(self.reference_angle_tab), _translate("MainWindow", "Reference Angle Zero"))
        self.scan_collection_tabs.setTabText(self.scan_collection_tabs.indexOf(self.angle_tab_1), _translate("MainWindow", "Angle 1"))

